### ISSUE TITLE
Pre-ceremony action items

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/psf-tuf-runbook#1]
The following tasks need to be accomplished before we can attempt the generation and signing ceremonies:

Purchases:
* Tamper-evident bags (one per HSM and flash storage, both pre and post ceremony = 24 total)
* Stick-on labels (one per tamper evident bag = 24 total)
* Trusted offline machines (one per signing body member = 6 total)
    * Current guidance: Raspberry Pi model 4s

**Comment by woodruffw** [comment]
Adapted purchase list for the online ceremony between me and @ewdurbin:

* **Exactly** one Raspberry Pi 3, Model B
* **Exactly** one microSD flash card, 32 GB
* One flash storage device for each HSM (6 total)
* One tamper evident bag for each pair of HSM + flash device (6 total)

I'll follow this comment with a collection of recommended purchase links.

**Comment by woodruffw** [comment]
Recommended purchase links:

* Raspberry Pi 3, Model B: [Adafruit](https://www.adafruit.com/product/3055?src=raspberrypi)
* 32GB microSD flash card: [Amazon](https://amazon.com/gp/product/B06XWMQ81P)
* Flash storage devices (bulk): [Amazon](https://www.amazon.com/SanDisk-Cruzer-Blade-8GB-SDCZ50-008G/dp/B07D7WFVK5)
* Tamper evident bags (bulk, includes labels): [Amazon](https://www.amazon.com/MMF-Industries-2362010N06-12-Inch-Tamper-Evident/dp/B000J05F06/)

**Comment by ewdurbin** [comment]
Thank you @woodruffw all of the listed items (as well as a backup microSD card and some fade resistant markers) have been ordered and will be in my possession by Tuesday August 25th.
